# _config.yml
title: 
email: lumtrav@gmail.com
description: >-
  Pointer to my pet projects
baseurl: ""
url: "https://butterbgud.github.io"
github_username:  butterbgud

# Minima theme settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-avatar

# Footer content comes from these variables in Minima
author: butterbgud
